language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  allow_failures:
    - php:
      - 7.0
      - hhvm

install:
  - composer install

script:
  - composer test

after_script:
  # @TODO: ocular or coveralls?
  cat build/testdox.txt  build/coverage.txt
